#!/bin/bash

set -e
set -u

function PrintUsage ()
{
	echo "Usage: ${0} {start|shutdown} containername"
	echo "       ${0} list (--all)"
	exit 1
}


if [ "$#" -eq 0 ]; then
	PrintUsage
fi

case ${1} in
"start")
	if [ "$#" -gt 1 ]; then
		lxc-start -d -n ${2}
	else
		PrintUsage
	fi
	;;
"shutdown")
	if [ "$#" -gt 1 ]; then
		lxc-stop -n ${2}
	else
		PrintUsage
	fi
	;;
"list")
	if [ "$#" -gt 1 ]; then
		case ${2} in
		"--all")
			lxc-ls --fancy
			;;
		case *)
			PrintUsage
			;;
		esac
	else
		lxc-ls --active --fancy
	fi
	;;
*)
	PrintUsage
	;;
esac

